Updates for compatibility for Terra upgrade (#2)
-major update for compatibility after Siemens Terra upgrade
-updated mcr to 2019a (mcr usage and download url path changed too)
-added UNI-DEN T1w generation (with default scaling factor=6)
-commented out all real-time figure generation
-enabled use of SA2RAGE without pre-computed B1map, but uses it when available (*)

(*): this was tested against pre-upgrade but required a re-scaling of the b1Div/UNI image to obtain same result — left this hard-coded re-scaling out; for backwards compatibility just make sure B1map is present

diff --git a/mp2rage_correction b/mp2rage_correction
--- a/mp2rage_correction
+++ b/mp2rage_correction
@@ -1,4 +1,6 @@
 #!/bin/bash
+execpath=`dirname $0`
+execpath=`realpath $execpath`
 
 function die {
  echo $1 >&2
@@ -209,34 +211,57 @@ fi
 
 
 
-b1map=`eval ls $in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_acq-b1map_SA2RAGE.nii.gz | head -n 1` 
-b1inv1=`eval ls "$in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_inv-1_SA2RAGE*.nii*" | head -n 1` 
-b1inv2=`eval ls "$in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_inv-2_SA2RAGE*.nii*" | head -n 1` 
+b1inv1=`eval ls "$in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_inv-1_*SA2RAGE.nii*" | head -n 1` 
+b1inv2=`eval ls "$in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_inv-2_*SA2RAGE.nii*" | head -n 1` 
+b1uni=`eval ls $in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_acq-{b1Div,UNI}_*SA2RAGE.nii* | head -n 1` 
+b1map=`eval ls $in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_acq-b1map_*SA2RAGE.nii* | head -n 1` 
+if [ ! -e "$b1map" ]
+then
+ nob1map=1
+ else
+	 nob1map=0
+ fi
 
-# iterate over runs and echos, by finding *MP2RAGE*T1map images
 
-for t1map in $in_bids/${subj_sess_dir}/anat/${subj_sess_prefix}*acq-MP2RAGE*T1map.nii* 
+#verify b1inv1 and b1inv2 exist
+if [ ! -e "$b1inv1" -o ! -e "$b1inv2" ]
+then
+	echo "Required SA2RAGE inv-1 or SA2RAGE inv-2 not found! (searched for: $in_bids/${subj_sess_dir}/fmap/${subj_sess_prefix}_inv-2_SA2RAGE*.nii*)"
+	exit 1
+fi
+
+# technically, we don't require the b1map if UNI/b1Div is provided
+if [ ! -e "$b1uni" ]
+then
+	echo "required Sa2RAGE UNI/b1Div does not exist!"
+	exit 1
+fi
+
+
+# iterate over runs and echos, by finding *_acq-UNI_*MP2RAGE images
+
+
+for t1uni in $in_bids/${subj_sess_dir}/anat/${subj_sess_prefix}*acq-UNI_*MP2RAGE.nii* 
 do
 
- beforeacq=${t1map%%_acq-MP2RAGE*}
+ echo t1uni: $t1uni
+ beforeacq=${t1uni%%_acq-UNI_*}
  beforeacq=${beforeacq##*/}
- afteracq=${t1map##*acq-MP2RAGE_}
- afteracq=${afteracq%%_T1map.*}
+ afteracq=${t1uni##*acq-UNI_}
+ afteracq=${afteracq%%_MP2RAGE.*}
 
+ echo beforeacq $beforeacq
+ echo afteracq $afteracq
 
- t1inv1=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}*inv-1*${afteracq}*MP2RAGE.nii*" | head -n 1`
- if [ ! -n "$t1inv1" ]; then echo "t1inv1 missing, skipping correction for $t1map"; continue; fi
- t1inv2=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}*inv-2*${afteracq}*MP2RAGE.nii*" | head -n 1`
- if [ ! -n "$t1inv2" ]; then echo "t1inv2 missing, skipping correction for $t1map"; continue; fi
- t1uni=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}*acq-UNI*${afteracq}*MP2RAGE.nii*" | head -n 1`
- if [ ! -n "$t1uni" ]; then echo "t1uni missing, skipping correction for $t1map"; continue; fi
- t1den=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}*acq-MP2RAGE*${afteracq}*T1w.nii*" | head -n 1`
- if [ ! -n "$t1den" ]; then echo "t1den missing, skipping correction for $t1map"; continue; fi
+ t1inv1=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}_inv-1_${afteracq}*MP2RAGE.nii*" | head -n 1`
+ if [ ! -n "$t1inv1" ]; then echo "t1inv1 missing, skipping correction for $t1uni"; continue; fi
+ t1inv2=`eval ls "$in_bids/${subj_sess_dir}/anat/${beforeacq}_inv-2_${afteracq}*MP2RAGE.nii*" | head -n 1`
+ if [ ! -n "$t1inv2" ]; then echo "t1inv2 missing, skipping correction for $t1uni"; continue; fi
 
+ echo b1uni: $b1uni
  echo b1map: $b1map
  echo b1inv1: $b1inv1
  echo b1inv2: $b1inv2
- echo t1map: $t1map
  echo t1uni: $t1uni
  echo t1inv1: $t1inv1
  echo t1inv2: $t1inv2
@@ -271,7 +296,7 @@ else
   echo "TIs=[`getValueJson.py $t1inv1_json InversionTime`,`getValueJson.py $t1inv2_json InversionTime`]" >> $t1_params
   NZ=`fslval $t1inv1 dim1`
   ResPE=`getValueJson.py $t1inv1_json AcquisitionMatrixPE`
-  NumPEsteps=`getValueJson.py $t1inv1_json global const NumberOfPhaseEncodingSteps`
+  NumPEsteps=`getValueJson.py $t1inv1_json PhaseEncodingSteps`
   PartialFourier=`bashcalc $NumPEsteps/$ResPE` 
   #NZslices = Slices Per Slab * [PartialFourierInSlice-0.5  0.5]
   echo "NZslices=[`bashcalc "$NZ*($PartialFourier - 0.5)"`,`bashcalc "$NZ*( 0.5)"`]" >> $t1_params
@@ -301,13 +326,22 @@ else
   echo "TR=`getValueJson.py $b1inv1_json RepetitionTime`" >> $b1_params
   echo "TRFLASH=$sa2rage_echo_spacing" >> $b1_params  #can get from PDF Protocol as Sequence: Echo Spacing
 
-  #for some reason, dicom tag for TI in Sa2RAGE in milliseconds instead of seconds, so need to divide by 1000
+  #for older scans, dicom tag for TI in Sa2RAGE in milliseconds instead of seconds, so need to divide by 1000
+  # if inversion time is greater than 10, then can assume we are in milliseconds (since TI=10s is way too large..) 
+ 
   TI1_ms=`getValueJson.py $b1inv1_json InversionTime` 
   TI2_ms=`getValueJson.py $b1inv2_json InversionTime`
-  echo "TIs=[${TI1_ms}e-3,${TI2_ms}e-3]" >> $b1_params
+  is_milliseconds=`bashcalc "$TI1_ms > 10"`
+  if [ "$is_milliseconds" = "1" ]
+  then
+    echo "InversionTime is assumed to be in milliseconds, accounting for this.."
+    echo "TIs=[${TI1_ms}e-3,${TI2_ms}e-3]" >> $b1_params
+    else
+    echo "TIs=[${TI1_ms},${TI2_ms}]" >> $b1_params
+  fi
   AccelPE=`getValueJson.py $b1inv1_json ParallelReductionFactorInPlane`
   ResPE=`getValueJson.py $b1inv1_json AcquisitionMatrixPE`
-  NumPEsteps=`getValueJson.py $b1inv1_json global const NumberOfPhaseEncodingSteps`
+  NumPEsteps=`getValueJson.py $b1inv1_json PhaseEncodingSteps`
   PartialFourier=`bashcalc $NumPEsteps/$ResPE` 
   #  Sa2RAGE.NZslices=128.*[0.25 0.5]./2 # Base Resolution * [PartialFourierInPE-0.5  0.5]/iPATpe  
   NZ1=`bashcalc "$ResPE*($PartialFourier - 0.5)/$AccelPE"`
@@ -319,7 +353,11 @@ fi
 
 #convert to float for precision
 t1uni_f=$work_dir/${t1uni##*/}
+if [ ! -e $t1uni_f ]
+then
+echo fslmaths $t1uni $t1uni_f -odt float 
 fslmaths $t1uni $t1uni_f -odt float 
+fi
 
 #now, register the sa2rage inv2 to the mp2rage inv2
 b1inv2_file=${b1inv2##*/}
@@ -331,32 +369,52 @@ echo flirt -v -nosearch -usesqform -in $b1inv2 -out $b1inv2_reg -omat $b1_to_t1 
 flirt -v -nosearch -usesqform -in $b1inv2 -out $b1inv2_reg -omat $b1_to_t1 -ref $t1inv2
 fi
 
-#transform sa2rage b1map to t1 space
+#transform sa2rage UNI to t1 space
+b1uni_file=${b1uni##*/}
+b1uni_reg=$work_dir/${b1uni_file%%.nii.gz}_space-T1w.nii.gz
+if [ ! -e $b1uni_reg ]
+then
+echo flirt -datatype float -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1uni -out $b1uni_reg -interp nearestneighbour
+flirt -datatype float -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1uni -out $b1uni_reg -interp nearestneighbour
+fi
+
+
+
+
+if [ "$nob1map" = "0" ]
+then
 b1map_file=${b1map##*/}
 b1map_reg=$work_dir/${b1map_file%%.nii.gz}_space-T1w.nii.gz
 if [ ! -e $b1map_reg ]
 then
-echo flirt -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1map -out $b1map_reg 
-flirt -datatype float -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1map -out $b1map_reg 
+echo flirt -datatype float -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1map -out $b1map_reg -interp nearestneighbour
+flirt -datatype float -applyxfm -init $b1_to_t1 -ref $t1inv2 -in $b1map -out $b1map_reg -interp nearestneighbour
+fi
+else
+	b1map_reg="";
 fi
 
-t1map_file=${t1map##*/}
-t1map_corr=$work_dir/${t1map_file%%_T1map.nii.gz}_proc-SA2RAGE_T1map.nii
+
+t1map_corr=$work_dir/${beforeacq}_acq-MP2RAGE_${afteracq}_proc-SA2RAGE_T1map.nii
+b1map_corr=$work_dir/${beforeacq}_acq-MP2RAGE_${afteracq}_proc-SA2RAGE_B1map.nii
 t1uni_file=${t1uni##*/}
 t1uni_corr=$work_dir/${t1uni_file%%_MP2RAGE.nii.gz}_proc-SA2RAGE_MP2RAGE.nii
+uni_den=$work_dir/${t1uni_file%%_MP2RAGE.nii.gz}_proc-SA2RAGE_T1w.nii
 
-if [ ! -e $t1map_corr ]
-then
-echo run_mp2rage_correction.sh $b1map_reg $t1uni_f $b1_params $t1_params $t1uni_corr $t1map_corr 
-run_mp2rage_correction.sh $b1map_reg $t1uni_f $b1_params $t1_params $t1uni_corr $t1map_corr 
-fi
+#if [ ! -e $t1map_corr ]
+#then
+echo "mp2rage_correction('$t1inv1','$t1inv2','$b1uni_reg','$t1uni_f','$b1_params','$t1_params','$t1uni_corr','$t1map_corr','$b1map_corr','$uni_den','$b1map_reg')"
+echo ${execpath}/mcr/${MCRVERSION}/run_mp2rage_correction.sh $MCRROOT $t1inv1 $t1inv2 $b1uni_reg $t1uni_f $b1_params $t1_params $t1uni_corr $t1map_corr $b1map_corr $uni_den $b1map_reg 
+${execpath}/mcr/${MCRVERSION}/run_mp2rage_correction.sh $MCRROOT $t1inv1 $t1inv2 $b1uni_reg $t1uni_f $b1_params $t1_params $t1uni_corr $t1map_corr $b1map_corr $uni_den $b1map_reg 
+#fi
 
-gzip $t1map_corr $t1uni_corr
+gzip $t1map_corr $t1uni_corr $b1map_corr $uni_den
 
 #copy to bids folder:
-out_deriv=$derivatives/$subj_sess_dir/anat
-mkdir -p $out_deriv
-cp -v ${t1map_corr}.gz ${t1uni_corr}.gz $out_deriv
+out_deriv=$derivatives/$subj_sess_dir
+mkdir -p $out_deriv/anat $out_deriv/fmap
+cp -v ${t1map_corr}.gz ${t1uni_corr}.gz ${uni_den}.gz $out_deriv/anat
+cp -v ${b1map_corr}.gz  $out_deriv/fmap
 
 done # loop through t1map inputs
 
